### ISSUE TITLE
Server crashes on startup with unpinned mcp>=1.6.0 — resolves to breaking mcp==2.0.0

### ISSUE THREAD

**Issue by inspiredearth** [garylab/pexels-mcp-server#2]
## Description

Installing via `uvx pexels-mcp-server` (or plain `pip install pexels-mcp-server`) currently pulls in `mcp==2.0.0`, since `pyproject.toml` specifies `mcp[cli]>=1.6.0` with no upper bound. `mcp` 2.0.0 removed/changed the `Server.list_tools` decorator API that `server.py` relies on, so the server crashes immediately on startup.

## Steps to reproduce

```bash
export PEXELS_API_KEY=<any key>
uvx pexels-mcp-server
```

## Actual behavior

```
Traceback (most recent call last):
  File ".../bin/pexels-mcp-server", line 6, in <module>
    from pexels_mcp_server import main
  File ".../pexels_mcp_server/__init__.py", line 3, in <module>
    from . import server
  File ".../pexels_mcp_server/server.py", line 42, in <module>
    @server.list_tools()
     ^^^^^^^^^^^^^^^^^
AttributeError: 'Server' object has no attribute 'list_tools'
```

## Expected behavior

Server starts cleanly and responds to the MCP `initialize` handshake.

## Root cause

`pyproject.toml` declares:
```
"mcp[cli]>=1.6.0"
```
with no upper bound. `mcp` 2.0.0 (released recently) is a breaking major version bump that changes the `Server` API surface this project's `server.py` was written against. Any fresh install today resolves to 2.0.0 and breaks.

## Suggested fix

Pin an upper bound compatible with the API this code actually uses, e.g.:
```
"mcp[cli]>=1.6.0,<2.0.0"
```
(then separately track a `mcp` 2.0 migration if desired).

## Workaround (confirmed working)

Pin the dependency at invocation time:
```bash
uvx --with "mcp<2.0" pexels-mcp-server
```
or in an MCP client config:
```json
{
  "command": "uvx",
  "args": ["--with", "mcp<2.0", "pexels-mcp-server"],
  "env": { "PEXELS_API_KEY": "..." }
}
```
Verified this starts cleanly and that `tools/list` and a live `photos_search` call both work correctly with `mcp<2.0` pinned.

## Environment

- `pexels-mcp-server` 0.0.4 (latest on PyPI as of report)
- Installed via `uv`/`uvx`
- macOS, Python 3.14
- `mcp` resolved to 2.0.0 without the pin

---

## Bonus (separate, minor) issue

While verifying the fix, I also noticed the `next_page` URL returned by `photos_search` (and likely other list endpoints) has a doubled path segment:
```
https://api.pexels.com/v1/v1/search?page=2&per_page=1&query=mountains
```
should presumably be `https://api.pexels.com/v1/search?...`. Harmless for most callers since the real Pexels endpoint is usually reconstructed from `page`/`per_page` params rather than following that link directly, but worth fixing since it'll 404 if followed as-is.
